version: "3.9"
services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mongo
    environment:
      PORT: 80
      JWT_SECRET: ${JWT_SECRET}
      MONGO_USERNAME: ${MONGO_APP_USERNAME}
      MONGO_PASSWORD: ${MONGO_APP_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}
      NOTION_CLIENT_SECRET: ${NOTION_CLIENT_SECRET}
      NOTION_CLIENT_ID: ${NOTION_CLIENT_ID}
      AES_SECRET: ${AES_SECRET}

  mongo:
    image: mongo
    volumes:
      - ${MONGO_FOLDER}:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: breeze
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}