version: "3.9"
services:
  mongo:
    image: mongo
    volumes:
      - ${MONGO_FOLDER}:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: breeze
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}